version: "3"

services:
  mysql:
    container_name: airflow-fastapi-mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: airflow_fastapi
      MYSQL_ROOT_PASSWORD: qweqwe123
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command: --authentication-policy=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping
      interval: "10s"
      timeout: "5s"
      start_period: "5s"
      retries: 3


volumes:
  mysql:
